# Docs: https://www.chezmoi.io/user-guide/include-files-from-elsewhere/
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/spaceship-prompt"]
    type = "archive"
    url = "https://github.com/spaceship-prompt/spaceship-prompt/archive/refs/tags/v3.16.7.tar.gz"
    exact = true
    stripComponents = 1

[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

{{ $ageVersion := "1.0.0" -}}
[".local/bin/age"]
    type = "file"
    url = "https://github.com/FiloSottile/age/releases/download/v{{ $ageVersion }}/age-v{{ $ageVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/age".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "age/age"]

[".local/bin/restic"]
    type = "file"
    url = "https://beta.restic.net/latest_restic_linux_amd64"
    executable = true
    refreshPeriod = "168h"

[".local/bin/autorestic"]
    type = "file"
    url = "https://github.com/cupcakearmy/autorestic/releases/download/v1.7.1/autorestic_1.7.1_linux_amd64.bz2"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/autorestic".filter]
        command = "bunzip2"

[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

